### ISSUE TITLE
Ошибки при запуске

### ISSUE THREAD

**Issue by FixFever** [konkere/TorrUpd#1]
Ошибка при запуске:
```
2024-09-29 21:29:42 During handling of the above exception, another exception occurred:
2024-09-29 21:29:42 
2024-09-29 21:29:42 Traceback (most recent call last):
2024-09-29 21:29:42   File "/app/torrent_updater.py", line 81, in <module>
2024-09-29 21:29:42     main()
2024-09-29 21:29:42   File "/app/torrent_updater.py", line 55, in main
2024-09-29 21:29:42     new_torrent = fresh_tracker.download_torrent()
2024-09-29 21:29:42   File "/app/tracker.py", line 94, in download_torrent
2024-09-29 21:29:42     torrent_fix = self.fix_announcers(torrent)
2024-09-29 21:29:42   File "/app/tracker.py", line 98, in fix_announcers
2024-09-29 21:29:42     torrent_decode = bdecode(torrent)
2024-09-29 21:29:42   File "bencoder.pyx", line 88, in bencoder.bdecode
2024-09-29 21:29:42   File "bencoder.pyx", line 84, in bencoder.bdecode2
2024-09-29 21:29:42 bencoder.BTFailure: not a valid bencoded string
2024-09-29 21:29:57 Traceback (most recent call last):
2024-09-29 21:29:57   File "bencoder.pyx", line 82, in bencoder.bdecode2
2024-09-29 21:29:57 KeyError: 60
```

Видимо не может распарсить торрент-файл, но непонятно даже какой именно

**Comment by FixFever** [comment]
Был указан неправильный логин/пароль к рутрекеру, после исправления ошибка ушла
